package docs:calculator@0.1.0;

// Describes the contract of a calculator.
interface calculate {
    // Operations supported by the calculator.
    enum op {
        add, subtract
    }

    // Evaluates an expression that applies an operation with two integers.
    eval-expression: func(op: op, x: s32, y: s32) -> s32;
}

// Describes the contract to add two integers.
interface add {
    // Returns the sum of two integers as an integer.
    add: func(a: s32, b: s32) -> s32;
}

// Defines the component that provides the addition operation.
world adder {
    export add;
}

// Describes the contract to subtract two integers.
interface subtract {
    // Subtracts integer `b` from integer `a`.
    subtract: func(a: s32, b: s32) -> s32;
}

// Defines the component that provides the subtraction operation.
world subtractor {
    export subtract;
}

// Defines the component that depends on an external party (component or Wasm
// host) to provide the implementation of the addition operation and provides a
// calculator implementation.
world calculator {
    import add;
    import subtract;
    export calculate;
}

// Defines the component that depends on an external party (component or Wasm
// host) to provide the implementation of a calculator.
world app {
    import calculate;
}