package calc:basic@0.1.0;

// Describes the contract of a calculator.
interface calculate {
    use types.{numeric};

    // Operations supported by the calculator.
    enum op {
        add, subtract
    }

    // Evaluates an expression that applies an operation with two integers.
    eval-expression: func(op: op, x: numeric, y: numeric) -> numeric;
}

// Defines the component that depends on an external party (component or Wasm
// host) to provide the implementation of the addition operation and provides a
// calculator implementation.
world calculator {
    import add;
    import subtract;
    export calculate;
}

// Defines the component that depends on an external party (component or Wasm
// host) to provide the implementation of a calculator.
world app {
    import calculate;
}